version: '3'
services:
  electrumx:
    image: lucky2077/atomicals-electrumx:latest
    restart: always
    ports:
      - 50004:50004
    volumes:
      - ./data:/data
    environment:
      - DAEMON_URL=${DAEMON_URL:-electrumx:electrumx@127.0.0.1:8332}
      - COIN=BitCoin
      