version: '3'
services:
  electrumx:
    build: .
    restart: always
    ports:
      - 50001:50001
      - 50002:50002
      - 50004:50004
      - 8000:8000
    volumes:
      - ./data-dev:/data
    environment:
      - DAEMON_URL=${DAEMON_URL:?}
      - COIN=BitCoin
      
