version: '3'
services:
  electrumx:
    image: lucky2077/atomicals-electrumx:v.1.3.8.0
    restart: always
    ports:
      - 50001:50001
      - 50002:50002
      - 8000:8000
      - 8080:8080
    healthcheck:
      test: "nc -z localhost 50001"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./electrumx-data:/data
    environment:
      - DAEMON_URL=nextdao:nextdao@127.0.0.1:8332
      - COIN=BitCoin
