version: '3'
services:
  electrumx:
    build: .
    restart: always
    ports:
      - 50001:50001
      - 50002:50002
      - 8000:8000
      - 8080:8080
    volumes:
      - ./electrumx-data-dev:/data
    environment:
      - DAEMON_URL=nextdao:nextdao@127.0.0.1:8332
      - COIN=BitCoin
