version: '3'
services:
  electrumx:
    image: lucky2077/atomicals-electrumx:latest
    restart: always
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      - DAEMON_URL=${DAEMON_URL:?}
      - COIN=BitCoin
      